import type { Action, DimensionId } from '@/types'
import { MARCHE, montant } from '@/config/market'

/**
 * Bibliothèque d'actions — 92 entrées.
 *
 * Règle d'écriture : une action générique tue le produit. « Ouvre un compte épargne » ne se fait pas.
 * « Ouvre un compte Wave et programme un virement de 5 000 F chaque vendredi » se fait ce soir.
 * Tout ce qui est local passe par `MARCHE` : changer de pays = éditer `src/config/market.ts`.
 *
 * `versionReduite` n'est pas un lot de consolation. C'est la même intention, à la taille d'une
 * semaine difficile — c'est ce que `adapt.ts` propose quand une action n'a pas été faite deux fois.
 *
 * `ceSoir` = faisable ce soir : sans rendez-vous, sans guichet ouvert, sans argent à sortir.
 */

const VILLE = MARCHE.villes[0]
const WAVE = MARCHE.paiement.principal
const GUICHET = MARCHE.administratif.guichetEntreprise

export const ACTIONS: Action[] = [
  // ————————————————————————————— SOI ET CONFIANCE —————————————————————————————
  {
    id: 'soi-trois-preuves',
    dimension: 'soi',
    titre: 'Écris trois choses que tu as réussies cette année, même minuscules.',
    pourquoi: 'On ne construit rien sur une mémoire qui n’enregistre que les échecs.',
    effortMinutes: 15,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Écris-en une seule.',
    ceSoir: true,
  },
  {
    id: 'soi-journal-3-lignes',
    dimension: 'soi',
    titre: 'Ce soir, écris trois lignes : ce que tu as fait, ce que tu as évité, ce que tu feras demain.',
    pourquoi: 'Trois lignes tiennent dans une journée chargée. Un journal, non.',
    effortMinutes: 5,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Écris seulement la troisième ligne : ce que tu feras demain.',
    ceSoir: true,
  },
  {
    id: 'soi-couper-notifs',
    dimension: 'soi',
    titre: 'Coupe les notifications d’un groupe qui te prend ton attention sans rien te donner.',
    pourquoi: 'Ton attention est la seule ressource que tu ne peux pas emprunter.',
    effortMinutes: 10,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Mets-le en silencieux pour huit heures, juste pour voir.',
    ceSoir: true,
  },
  {
    id: 'soi-ecrire-peur',
    dimension: 'soi',
    titre: 'Écris en entier ce qui te fait le plus peur dans ce que tu prépares.',
    pourquoi: 'Une peur écrite arrête de grossir dans le noir.',
    effortMinutes: 15,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Écris juste les cinq premiers mots.',
    ceSoir: true,
  },
  {
    id: 'soi-desencombrer',
    dimension: 'soi',
    titre: 'Range un seul endroit que tu vois chaque matin.',
    pourquoi: 'Un endroit net le matin change l’humeur de la première heure.',
    effortMinutes: 20,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Range une étagère. Une seule.',
    ceSoir: true,
  },
  {
    id: 'soi-sommeil-alarme',
    dimension: 'soi',
    titre: 'Choisis une heure de coucher et mets une alarme qui te le rappelle.',
    pourquoi: 'Tout est plus dur quand tu dors cinq heures. Tout.',
    effortMinutes: 5,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Mets l’alarme trois soirs, pas sept.',
    ceSoir: true,
  },
  {
    id: 'soi-marche-seule',
    dimension: 'soi',
    titre: 'Marche trente minutes seule, sans téléphone, une fois cette semaine.',
    pourquoi: 'Les décisions se prennent en marchant, pas devant un écran.',
    effortMinutes: 30,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Marche dix minutes, téléphone en poche, en silencieux.',
  },
  {
    id: 'soi-relire-vision',
    dimension: 'soi',
    titre: 'Relis à voix haute ce que tu as écrit le premier jour.',
    pourquoi: 'Entendre ta propre phrase ne fait pas le même effet que la lire.',
    effortMinutes: 5,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Relis-la en silence.',
    ceSoir: true,
  },
  {
    id: 'soi-phrase-presentation',
    dimension: 'soi',
    titre: 'Écris en une phrase ce que tu fais, sans t’excuser et sans « juste ».',
    pourquoi: 'Tu vas la dire cent fois cette année. Autant qu’elle soit à toi.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Écris les cinq mots qui doivent y être.',
    ceSoir: true,
  },
  {
    id: 'soi-non-negociables',
    dimension: 'soi',
    titre: 'Écris trois choses que tu n’accepteras plus.',
    pourquoi: 'Une limite écrite se tient mieux qu’une limite pensée.',
    effortMinutes: 25,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Écris-en une, la plus évidente.',
    ceSoir: true,
  },
  {
    id: 'soi-dire-non',
    dimension: 'soi',
    titre: 'Dis non une fois cette semaine à une demande qui n’est pas la tienne.',
    pourquoi: 'Chaque oui automatique est du temps pris à ton projet.',
    effortMinutes: 10,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Réponds « je te dis demain » au lieu d’un oui immédiat.',
  },
  {
    id: 'soi-heure-a-toi',
    dimension: 'soi',
    titre: 'Bloque une heure dans ton téléphone cette semaine, à ton nom.',
    pourquoi: 'Ce qui n’est pas dans l’agenda n’existe pas.',
    effortMinutes: 60,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Bloque vingt minutes.',
    ceSoir: true,
  },
  {
    id: 'soi-inventaire-energie',
    dimension: 'soi',
    titre: 'Pendant trois jours, note ce qui te vide et ce qui te remplit.',
    pourquoi: 'Tu ne peux pas protéger ton énergie tant que tu ne sais pas où elle part.',
    effortMinutes: 20,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Note-le une seule journée.',
  },
  {
    id: 'soi-arreter-une-chose',
    dimension: 'soi',
    titre: 'Choisis une tâche que tu fais par habitude, et arrête-la cette semaine.',
    pourquoi: 'Ajouter sans retirer, c’est comme ça qu’un plan devient invivable.',
    effortMinutes: 15,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Nomme-la, sans encore l’arrêter.',
    ceSoir: true,
  },
  {
    id: 'soi-liste-appris',
    dimension: 'soi',
    titre: 'Liste ce que tu as appris à faire seule ces trois dernières années.',
    pourquoi: 'Tu sous-estimes ce que tu as appris sans qu’on te le certifie.',
    effortMinutes: 25,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Écris-en trois.',
    ceSoir: true,
  },
  {
    id: 'soi-prendre-parole',
    dimension: 'soi',
    titre: 'Prends la parole une fois en réunion cette semaine, même pour reformuler.',
    pourquoi: 'On confie les choses à celles qu’on a entendues parler.',
    effortMinutes: 15,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Pose une question. Une question compte.',
  },
  {
    id: 'soi-rdv-sante',
    dimension: 'soi',
    titre: 'Prends le rendez-vous médical que tu repousses depuis des mois.',
    pourquoi: 'Rien de ce que tu prépares ne tient sans toi.',
    effortMinutes: 45,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Appelle juste pour demander les horaires.',
  },
  {
    id: 'soi-chose-repoussee',
    dimension: 'soi',
    titre: 'Fais une chose que tu repousses depuis plus d’un mois. La plus petite des trois.',
    pourquoi: 'Ce qui traîne coûte plus en poids mental qu’en temps réel.',
    effortMinutes: 40,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Écris les trois, et entoure la plus petite.',
  },
  {
    id: 'soi-demander-retour',
    dimension: 'soi',
    titre: 'Demande à deux personnes de confiance ce qu’elles te voient faire vraiment bien.',
    pourquoi: 'Ta valeur est souvent plus visible de l’extérieur que de l’intérieur.',
    effortMinutes: 30,
    difficulte: 3,
    prerequis: ['soi-phrase-presentation'],
    versionReduite: 'Demande à une seule personne, par message.',
  },
  {
    id: 'soi-refuser-gratuit',
    dimension: 'soi',
    titre: 'Refuse une fois de travailler gratuitement. Poliment, mais refuse.',
    pourquoi: 'Le prix que tu acceptes une fois devient le prix qu’on attend de toi.',
    effortMinutes: 20,
    difficulte: 3,
    prerequis: ['soi-phrase-presentation'],
    versionReduite: 'Prépare la phrase de refus, sans encore l’envoyer.',
  },

  // ————————————————————————————— CARRIÈRE —————————————————————————————
  {
    id: 'car-linkedin-titre',
    dimension: 'carriere',
    titre: `Change ton titre ${MARCHE.reseaux.pro} pour ce que tu veux faire, pas ce que tu fais.`,
    pourquoi: 'C’est la ligne que les gens lisent avant de décider de t’écrire.',
    effortMinutes: 20,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Écris le titre dans tes notes, sans le publier.',
    ceSoir: true,
  },
  {
    id: 'car-message-ancien-collegue',
    dimension: 'carriere',
    titre: 'Écris à un ancien collègue, juste pour reprendre contact.',
    pourquoi: 'Les opportunités passent par les liens tièdes, pas par les liens forts.',
    effortMinutes: 15,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Écris le message, envoie-le demain.',
    ceSoir: true,
  },
  {
    id: 'car-competence-manquante',
    dimension: 'carriere',
    titre: 'Écris la compétence qui te manque le plus pour la suite.',
    pourquoi: 'Nommer le manque, c’est déjà le rendre comblable.',
    effortMinutes: 20,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Écris-la en trois mots.',
    ceSoir: true,
  },
  {
    id: 'car-veille',
    dimension: 'carriere',
    titre: 'Abonne-toi à deux sources sérieuses de ton secteur.',
    pourquoi: 'On négocie mieux quand on sait ce qui se passe ailleurs.',
    effortMinutes: 15,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Une seule source suffit.',
    ceSoir: true,
  },
  {
    id: 'car-trois-realisations',
    dimension: 'carriere',
    titre: 'Écris trois réalisations chiffrées de ton poste actuel.',
    pourquoi: 'Sans chiffres, ton travail reste une impression.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Écris-en une, avec un seul chiffre.',
    ceSoir: true,
  },
  {
    id: 'car-poste-interne',
    dimension: 'carriere',
    titre: 'Regarde les postes ouverts en interne et note ceux qui te vont.',
    pourquoi: 'Partir n’est pas toujours la seule sortie.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Regarde la liste, sans rien noter.',
  },
  {
    id: 'car-preavis-verifier',
    dimension: 'carriere',
    titre: 'Relis ton contrat : préavis, clause de non-concurrence, solde de congés.',
    pourquoi: 'On décide mal quand on ne connaît pas les règles du jeu.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Cherche seulement la durée du préavis.',
    ceSoir: true,
  },
  {
    id: 'car-cv-a-jour',
    dimension: 'carriere',
    titre: 'Mets ton CV à jour, même si tu ne cherches rien aujourd’hui.',
    pourquoi: 'Un CV à jour te fait dire oui à une occasion qui ne prévient pas.',
    effortMinutes: 60,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Mets à jour seulement ton poste actuel.',
  },
  {
    id: 'car-liste-employeurs',
    dimension: 'carriere',
    titre: `Liste dix employeurs ou clients possibles à ${VILLE} ou ailleurs.`,
    pourquoi: 'Chercher sans liste, c’est attendre.',
    effortMinutes: 40,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Écris-en trois.',
  },
  {
    id: 'car-formation-identifier',
    dimension: 'carriere',
    titre: 'Trouve une formation courte qui te manque, et note son prix et ses dates.',
    pourquoi: 'Une formation sans prix ni date reste une intention.',
    effortMinutes: 45,
    difficulte: 2,
    prerequis: ['car-competence-manquante'],
    versionReduite: 'Note seulement le nom de la formation.',
  },
  {
    id: 'car-cafe-metier',
    dimension: 'carriere',
    titre: 'Prends un café avec quelqu’un qui fait déjà le métier que tu vises.',
    pourquoi: 'Une heure avec quelqu’un qui y est vaut trois mois de recherche.',
    effortMinutes: 45,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Envoie le message. Le café viendra après.',
  },
  {
    id: 'car-tarif-marche',
    dimension: 'carriere',
    titre: 'Demande à deux personnes du métier ce qu’elles facturent ou ce qu’elles gagnent.',
    pourquoi: 'Le silence sur les salaires ne protège que celui qui paie.',
    effortMinutes: 45,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Demande à une seule, en privé.',
  },
  {
    id: 'car-candidature-type',
    dimension: 'carriere',
    titre: 'Écris une candidature type que tu adapteras ensuite en dix minutes.',
    pourquoi: 'Le premier envoi coûte deux heures. Les suivants doivent en coûter dix minutes.',
    effortMinutes: 60,
    difficulte: 2,
    prerequis: ['car-trois-realisations'],
    versionReduite: 'Écris seulement le premier paragraphe.',
  },
  {
    id: 'car-augmentation-preparer',
    dimension: 'carriere',
    titre: 'Prépare ta demande d’augmentation : les chiffres, la date, la première phrase.',
    pourquoi: 'On ne négocie pas bien en improvisant dans un couloir.',
    effortMinutes: 60,
    difficulte: 3,
    prerequis: ['car-trois-realisations'],
    versionReduite: 'Écris seulement la première phrase.',
  },
  {
    id: 'car-augmentation-demander',
    dimension: 'carriere',
    titre: 'Demande le rendez-vous.',
    pourquoi: 'La préparation ne sert à rien tant que la date n’est pas posée.',
    effortMinutes: 30,
    difficulte: 3,
    prerequis: ['car-augmentation-preparer'],
    versionReduite: 'Écris le message de demande, garde-le en brouillon.',
  },
  {
    id: 'car-entretien-blanc',
    dimension: 'carriere',
    titre: 'Fais un entretien blanc avec quelqu’un qui recrute pour de vrai.',
    pourquoi: 'La première fois où tu dis ton parcours à voix haute ne doit pas être la bonne.',
    effortMinutes: 60,
    difficulte: 3,
    prerequis: ['car-trois-realisations'],
    versionReduite: 'Enregistre-toi deux minutes sur ton téléphone, et réécoute.',
  },
  {
    id: 'car-portfolio',
    dimension: 'carriere',
    titre: 'Fais une page qui montre ton travail. Une seule page.',
    pourquoi: 'Montrer coupe court à dix minutes d’explications.',
    effortMinutes: 90,
    difficulte: 3,
    prerequis: ['car-trois-realisations'],
    versionReduite: 'Rassemble trois exemples dans un dossier, sans mise en page.',
  },
  {
    id: 'car-date-sortie',
    dimension: 'carriere',
    titre: 'Pose une date approximative pour ton départ. Au crayon, mais pose-la.',
    pourquoi: 'Sans date, « bientôt » dure trois ans.',
    effortMinutes: 45,
    difficulte: 3,
    prerequis: ['car-preavis-verifier'],
    versionReduite: 'Choisis seulement le trimestre.',
  },

  // ————————————————————————————— FINANCES —————————————————————————————
  {
    id: 'fin-releve-30j',
    dimension: 'finances',
    titre: 'Ouvre ton relevé et lis les trente derniers jours, ligne par ligne.',
    pourquoi: 'On ne peut pas décider sur un chiffre qu’on n’a pas regardé.',
    effortMinutes: 25,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Lis seulement les sept derniers jours.',
    ceSoir: true,
  },
  {
    id: 'fin-abonnements',
    dimension: 'finances',
    titre: 'Liste tes abonnements et coupes-en un.',
    pourquoi: 'Un prélèvement oublié, c’est de l’argent qui part sans avoir été décidé.',
    effortMinutes: 20,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Fais la liste. Coupe la semaine prochaine.',
    ceSoir: true,
  },
  {
    id: 'fin-depense-fuite',
    dimension: 'finances',
    titre: 'Repère la dépense qui revient chaque semaine sans que tu l’aies décidée.',
    pourquoi: 'Les fuites sont petites et régulières — c’est pour ça qu’on ne les voit pas.',
    effortMinutes: 15,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Regarde seulement tes trois derniers samedis.',
    ceSoir: true,
  },
  {
    id: 'fin-carnet-7-jours',
    dimension: 'finances',
    titre: 'Note toutes tes dépenses pendant sept jours. Toutes, même les cent francs.',
    pourquoi: 'Sept jours suffisent à voir le motif. Un mois, tu abandonnes avant.',
    effortMinutes: 20,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Note-les trois jours.',
    ceSoir: true,
  },
  {
    id: 'fin-dette-lister',
    dimension: 'finances',
    titre: 'Écris tout ce que tu dois : à qui, combien, depuis quand.',
    pourquoi: 'Une dette qu’on n’a pas écrite reste plus lourde qu’elle n’est.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Écris seulement la plus petite et la plus grosse.',
    ceSoir: true,
  },
  {
    id: 'fin-wave-auto',
    dimension: 'finances',
    titre: `Ouvre un compte ${WAVE} et programme un virement de ${montant(MARCHE.montants.microEpargneHebdo)} chaque vendredi.`,
    pourquoi: 'L’épargne qui demande une décision chaque semaine ne survit pas au deuxième mois.',
    effortMinutes: 20,
    difficulte: 2,
    prerequis: [],
    versionReduite: `Fais un seul virement de ${montant(1000)} cette semaine, à la main.`,
  },
  {
    id: 'fin-trois-categories',
    dimension: 'finances',
    titre: 'Range tes dépenses du mois en trois tas : vital, confort, fuite.',
    pourquoi: 'Trois catégories, tu tiens. Douze, tu arrêtes au bout de dix jours.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: ['fin-releve-30j'],
    versionReduite: 'Classe seulement les dix plus grosses lignes.',
  },
  {
    id: 'fin-revenu-reel',
    dimension: 'finances',
    titre: 'Calcule ce qui te reste vraiment chaque mois, une fois tout payé.',
    pourquoi: 'C’est ce chiffre-là, pas ton salaire, qui décide de ce que tu peux tenter.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Estime-le à la louche, à cinq mille francs près.',
  },
  {
    id: 'fin-facture-relance',
    dimension: 'finances',
    titre: 'Relance une facture impayée. Un message court suffit.',
    pourquoi: 'L’argent qu’on te doit ne revient pas tout seul.',
    effortMinutes: 20,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Écris le message, envoie-le demain matin.',
    ceSoir: true,
  },
  {
    id: 'fin-enveloppe-projet',
    dimension: 'finances',
    titre: 'Sépare l’argent du projet de l’argent de la maison. Deux comptes, ou deux enveloppes.',
    pourquoi: 'Tant que c’est mélangé, tu ne sauras jamais si ton projet gagne de l’argent.',
    effortMinutes: 25,
    difficulte: 2,
    prerequis: [],
    versionReduite: `Ouvre un deuxième compte ${WAVE}, sans encore rien y mettre.`,
  },
  {
    id: 'fin-banque-frais',
    dimension: 'finances',
    titre: 'Demande à ta banque la liste de tes frais du dernier trimestre.',
    pourquoi: 'Les frais bancaires se négocient — mais seulement quand on les a sous les yeux.',
    effortMinutes: 35,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Cherche la ligne « frais » sur ton dernier relevé.',
  },
  {
    id: 'fin-tontine',
    dimension: 'finances',
    titre: 'Renseigne-toi sur une tontine sérieuse autour de toi, et sur ce qu’elle te coûte vraiment.',
    pourquoi: 'La tontine marche quand on sait exactement à quel tour on passe.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Demande à une personne comment marche la sienne.',
  },
  {
    id: 'fin-coussin-objectif',
    dimension: 'finances',
    titre: `Fixe ton premier palier d’épargne : ${montant(MARCHE.montants.coussinPremierPalier)}.`,
    pourquoi: 'Un objectif atteignable en trois mois se tient. Un an, non.',
    effortMinutes: 20,
    difficulte: 2,
    prerequis: ['fin-revenu-reel'],
    versionReduite: 'Fixe la moitié du palier.',
  },
  {
    id: 'fin-aide-dispositif',
    dimension: 'finances',
    titre: `Cherche un dispositif d’appui aux entrepreneures (${GUICHET}, ONG, banque) et note ce qu’il demande.`,
    pourquoi: 'Beaucoup d’aides existent et ne sont pas prises, faute d’avoir lu la liste des pièces.',
    effortMinutes: 45,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Trouve juste le nom d’un dispositif et son site.',
  },
  {
    id: 'fin-dette-plan',
    dimension: 'finances',
    titre: 'Choisis ta plus petite dette et fixe-lui une date de fin.',
    pourquoi: 'Solder la plus petite d’abord ne rapporte pas le plus — ça donne juste la preuve que c’est possible.',
    effortMinutes: 45,
    difficulte: 3,
    prerequis: ['fin-dette-lister'],
    versionReduite: 'Écris la date, sans encore le montant mensuel.',
  },
  {
    id: 'fin-prix-plancher',
    dimension: 'finances',
    titre: 'Calcule le prix en dessous duquel tu perds de l’argent.',
    pourquoi: 'Sans ce chiffre, chaque négociation se fait à ton désavantage.',
    effortMinutes: 40,
    difficulte: 3,
    prerequis: ['fin-revenu-reel'],
    versionReduite: 'Compte seulement le coût de la matière, sans ton temps.',
  },
  {
    id: 'fin-negocier-charge',
    dimension: 'finances',
    titre: 'Renégocie une charge fixe : loyer, forfait, assurance, école.',
    pourquoi: 'Une charge fixe négociée une fois te rapporte tous les mois.',
    effortMinutes: 45,
    difficulte: 3,
    prerequis: ['fin-releve-30j'],
    versionReduite: 'Compare seulement ton forfait à deux autres offres.',
  },
  {
    id: 'fin-parler-argent',
    dimension: 'finances',
    titre: 'Parle argent une fois, franchement, avec la personne qui partage tes dépenses.',
    pourquoi: 'Les non-dits sur l’argent coûtent plus cher que l’argent lui-même.',
    effortMinutes: 40,
    difficulte: 3,
    prerequis: [],
    versionReduite: 'Prépare les trois phrases que tu veux dire.',
  },
  {
    id: 'fin-mois-sans',
    dimension: 'finances',
    titre: 'Choisis une catégorie de dépense et passe un mois sans.',
    pourquoi: 'Un mois sans te dit ce qui te manque vraiment. Souvent : rien.',
    effortMinutes: 60,
    difficulte: 3,
    prerequis: ['fin-trois-categories'],
    versionReduite: 'Fais-le une semaine.',
  },
  {
    id: 'fin-objectif-3mois',
    dimension: 'finances',
    titre: `Fixe le montant qui te ferait tenir trois mois sans revenu : environ ${montant(MARCHE.montants.coussinTroisMois)}.`,
    pourquoi: 'C’est ce chiffre qui décide de la date où tu peux partir.',
    effortMinutes: 30,
    difficulte: 3,
    prerequis: ['fin-coussin-objectif'],
    versionReduite: 'Calcule seulement ce que te coûte un mois.',
  },

  // ————————————————————————————— PROJET —————————————————————————————
  {
    id: 'pro-une-phrase',
    dimension: 'projet',
    titre: 'Écris ton offre en une phrase : à qui, quoi, pour combien.',
    pourquoi: 'Tant que ça ne tient pas en une phrase, ça ne tient pas dans la tête d’une cliente.',
    effortMinutes: 20,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Écris seulement le « à qui ».',
    ceSoir: true,
  },
  {
    id: 'pro-statut-whatsapp',
    dimension: 'projet',
    titre: `Mets ce que tu fais en statut ${MARCHE.reseaux.conversation}. Une phrase, pas une affiche.`,
    pourquoi: 'Tes premières clientes sont déjà dans tes contacts.',
    effortMinutes: 15,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Écris le statut. Publie-le quand tu seras prête.',
    ceSoir: true,
  },
  {
    id: 'pro-dix-noms',
    dimension: 'projet',
    titre: 'Écris dix prénoms de personnes qui pourraient acheter. Vraiment dix.',
    pourquoi: 'Une cible sans prénoms, c’est une idée. Avec dix prénoms, c’est un carnet.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Écris-en trois.',
    ceSoir: true,
  },
  {
    id: 'pro-message-type',
    dimension: 'projet',
    titre: 'Écris le message que tu enverras quand une cliente demandera le prix.',
    pourquoi: 'C’est le moment où on bafouille et où on baisse le prix.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: ['pro-une-phrase'],
    versionReduite: 'Écris seulement la phrase qui annonce le montant.',
    ceSoir: true,
  },
  {
    id: 'pro-carnet-commandes',
    dimension: 'projet',
    titre: 'Ouvre un carnet de commandes, même un cahier. Une ligne par demande.',
    pourquoi: 'Ce qui n’est pas écrit se perd, et une demande perdue ne revient pas.',
    effortMinutes: 25,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Note les trois dernières demandes que tu as eues.',
    ceSoir: true,
  },
  {
    id: 'pro-heure-projet',
    dimension: 'projet',
    titre: 'Bloque une heure de projet, à un moment où personne ne te demande rien.',
    pourquoi: 'Le projet ne prendra jamais la place qu’on ne lui a pas donnée.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Bloque vingt minutes, très tôt ou très tard.',
    ceSoir: true,
  },
  {
    id: 'pro-concurrente-etudier',
    dimension: 'projet',
    titre: 'Choisis une personne qui fait la même chose, et note tout ce qu’elle fait bien.',
    pourquoi: 'Copier la structure n’est pas copier — c’est gagner six mois.',
    effortMinutes: 40,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Note trois choses seulement.',
  },
  {
    id: 'pro-photos',
    dimension: 'projet',
    titre: 'Fais dix photos correctes de ton travail, au téléphone, à la lumière du jour.',
    pourquoi: 'On achète ce qu’on voit. Une photo sombre coûte des clientes.',
    effortMinutes: 45,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Fais-en trois, d’un seul produit.',
  },
  {
    id: 'pro-nom-projet',
    dimension: 'projet',
    titre: `Arrête un nom. Vérifie qu’il est libre sur ${MARCHE.reseaux.vitrine} et au ${MARCHE.administratif.registreCommerce}.`,
    pourquoi: 'Changer de nom après six mois coûte tout ce que tu auras construit autour.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Fais une liste de cinq noms, sans encore choisir.',
  },
  {
    id: 'pro-refus-analyse',
    dimension: 'projet',
    titre: 'Note les trois dernières fois où on t’a dit non, et ce qui a été dit exactement.',
    pourquoi: 'Les non contiennent l’information que les oui ne donnent pas.',
    effortMinutes: 25,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Note-en un seul.',
    ceSoir: true,
  },
  {
    id: 'pro-livraison',
    dimension: 'projet',
    titre: 'Décide comment tu livres, et combien ça te coûte vraiment.',
    pourquoi: 'La livraison mange la marge de la moitié des petites activités.',
    effortMinutes: 40,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Demande à deux livreurs leur tarif.',
  },
  {
    id: 'pro-page-vitrine',
    dimension: 'projet',
    titre: `Ouvre un compte ${MARCHE.reseaux.vitrine} dédié, avec trois publications. Pas trente.`,
    pourquoi: 'Trois publications suffisent pour qu’on te prenne au sérieux. Attendre d’en avoir trente, non.',
    effortMinutes: 60,
    difficulte: 2,
    prerequis: ['pro-photos'],
    versionReduite: 'Crée le compte et mets la photo de profil.',
  },
  {
    id: 'pro-temoignage',
    dimension: 'projet',
    titre: 'Demande une phrase de retour à ta première cliente.',
    pourquoi: 'Une phrase vraie vaut mieux qu’une page de promesses.',
    effortMinutes: 20,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Demande-lui juste si elle recommanderait, oui ou non.',
  },
  {
    id: 'pro-appeler-trois',
    dimension: 'projet',
    titre: 'Appelle trois personnes de ta liste et demande ce qui leur manque aujourd’hui.',
    pourquoi: 'Elles vont te dire ce qu’il faut vendre. Gratuitement.',
    effortMinutes: 45,
    difficulte: 3,
    prerequis: ['pro-dix-noms'],
    versionReduite: 'Appelles-en une.',
  },
  {
    id: 'pro-prix-afficher',
    dimension: 'projet',
    titre: 'Affiche tes prix. En public.',
    pourquoi: 'Les prix cachés attirent les négociations, pas les clientes.',
    effortMinutes: 30,
    difficulte: 3,
    prerequis: ['pro-une-phrase'],
    versionReduite: 'Envoie tes prix à trois personnes en privé.',
  },
  {
    id: 'pro-cout-unite',
    dimension: 'projet',
    titre: 'Calcule ce que te coûte une unité : matière, transport, et ton temps.',
    pourquoi: 'Beaucoup d’activités tournent à perte sans le savoir, parce que le temps n’est pas compté.',
    effortMinutes: 45,
    difficulte: 3,
    prerequis: [],
    versionReduite: 'Compte seulement la matière.',
  },
  {
    id: 'pro-premiere-vente',
    dimension: 'projet',
    titre: 'Vends une fois. Même petit, mais à quelqu’un qui paie vraiment.',
    pourquoi: 'Le premier paiement change ce que tu crois possible. Rien d’autre ne le fait.',
    effortMinutes: 60,
    difficulte: 3,
    prerequis: ['pro-une-phrase'],
    versionReduite: 'Propose ton offre à une seule personne, par message.',
  },
  {
    id: 'pro-offre-test',
    dimension: 'projet',
    titre: `Fabrique une version minimale de ton offre et fais-la essayer à trois personnes (budget ${montant(MARCHE.montants.budgetTestOffre)}).`,
    pourquoi: 'Tester coûte moins cher que se tromper en grand.',
    effortMinutes: 120,
    difficulte: 3,
    prerequis: ['pro-une-phrase'],
    versionReduite: 'Fais-la essayer à une seule personne.',
  },
  {
    id: 'pro-guichet',
    dimension: 'projet',
    titre: `Appelle le ${GUICHET} et note la liste exacte des pièces pour une ${MARCHE.administratif.statutSimple}.`,
    pourquoi: 'La formalisation bloque rarement sur l’argent — presque toujours sur une pièce manquante.',
    effortMinutes: 90,
    difficulte: 3,
    prerequis: ['pro-nom-projet'],
    versionReduite: 'Trouve seulement le numéro et les horaires.',
  },
  {
    id: 'pro-associee',
    dimension: 'projet',
    titre: 'Écris ce que tu attendrais d’une associée. Puis décide si tu en veux une.',
    pourquoi: 'La plupart des associations se défont sur ce qui n’a pas été écrit au début.',
    effortMinutes: 45,
    difficulte: 3,
    prerequis: [],
    versionReduite: 'Écris seulement ce que tu ne veux pas partager.',
  },

  // ————————————————————————————— FAMILLE ET ENTOURAGE —————————————————————————————
  {
    id: 'ent-vocal-amie',
    dimension: 'entourage',
    titre: 'Envoie un vocal à une amie pour lui dire ce que tu prépares.',
    pourquoi: 'Dire à voix haute rend la chose réelle, et te donne une témoin.',
    effortMinutes: 10,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Écris-le en message, si le vocal est trop.',
    ceSoir: true,
  },
  {
    id: 'ent-dire-merci',
    dimension: 'entourage',
    titre: 'Écris à quelqu’un qui t’a aidée, et dis précisément ce que ça a changé.',
    pourquoi: 'Les liens s’entretiennent quand tout va bien, pas quand on a besoin.',
    effortMinutes: 10,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Un message de deux lignes suffit.',
    ceSoir: true,
  },
  {
    id: 'ent-reseau-liste',
    dimension: 'entourage',
    titre: 'Écris les vingt personnes que tu connais qui pourraient t’ouvrir une porte.',
    pourquoi: 'Ton réseau est plus grand que ce que tu crois — il n’est juste pas écrit.',
    effortMinutes: 25,
    difficulte: 1,
    prerequis: [],
    versionReduite: 'Écris-en cinq.',
    ceSoir: true,
  },
  {
    id: 'ent-demander-service',
    dimension: 'entourage',
    titre: 'Demande un vrai service à quelqu’un. Pas un service poli.',
    pourquoi: 'Demander crée du lien. Ne jamais demander en crée aussi, mais pas le bon.',
    effortMinutes: 15,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Écris la demande, envoie-la quand tu veux.',
    ceSoir: true,
  },
  {
    id: 'ent-limite-horaire',
    dimension: 'entourage',
    titre: 'Décide une heure après laquelle tu ne réponds plus aux messages. Et dis-le.',
    pourquoi: 'Une limite annoncée est tenue deux fois plus souvent qu’une limite silencieuse.',
    effortMinutes: 20,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Décide l’heure, sans encore l’annoncer.',
    ceSoir: true,
  },
  {
    id: 'ent-groupe-soutien',
    dimension: 'entourage',
    titre: `Crée un groupe ${MARCHE.reseaux.conversation} avec trois personnes qui te veulent du bien.`,
    pourquoi: 'Un petit groupe qui sait ce que tu prépares vaut mille abonnés.',
    effortMinutes: 25,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Choisis les trois noms, sans créer le groupe.',
    ceSoir: true,
  },
  {
    id: 'ent-deux-femmes',
    dimension: 'entourage',
    titre: 'Trouve deux femmes qui font déjà ce que tu veux faire, et écris-leur.',
    pourquoi: 'Le chemin est plus court quand quelqu’un l’a déjà balisé.',
    effortMinutes: 30,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Trouve-en une, et lis ce qu’elle publie.',
  },
  {
    id: 'ent-garde',
    dimension: 'entourage',
    titre: 'Organise une garde régulière, même une seule fois par semaine.',
    pourquoi: 'Deux heures régulières valent mieux qu’une journée entière une fois par mois.',
    effortMinutes: 40,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Demande à une personne si elle serait disponible, sans fixer de date.',
  },
  {
    id: 'ent-evenement',
    dimension: 'entourage',
    titre: 'Va à un événement de ton secteur. Parle à deux personnes, pas à zéro.',
    pourquoi: 'Y aller sans parler à personne, c’est du temps perdu deux fois.',
    effortMinutes: 90,
    difficulte: 2,
    prerequis: [],
    versionReduite: 'Repère un événement et note la date.',
  },
  {
    id: 'ent-repartir-taches',
    dimension: 'entourage',
    titre: 'Écris tout ce que tu portes à la maison, et propose d’en confier deux.',
    pourquoi: 'La charge invisible reste invisible tant qu’elle n’est pas sur une feuille.',
    effortMinutes: 45,
    difficulte: 3,
    prerequis: [],
    versionReduite: 'Écris la liste. La conversation viendra après.',
  },
  {
    id: 'ent-annoncer',
    dimension: 'entourage',
    titre: 'Dis à une personne proche ce que tu es en train de faire. En entier.',
    pourquoi: 'Le secret protège de la critique, mais aussi de l’aide.',
    effortMinutes: 30,
    difficulte: 3,
    prerequis: ['ent-vocal-amie'],
    versionReduite: 'Dis-en la moitié. La moitié, c’est déjà dit.',
  },
  {
    id: 'ent-dire-non-famille',
    dimension: 'entourage',
    titre: 'Dis à une personne de ta famille que tu ne pourras pas, cette fois.',
    pourquoi: 'Ce que tu donnes par défaut ne te sera jamais rendu par défaut.',
    effortMinutes: 20,
    difficulte: 3,
    prerequis: [],
    versionReduite: 'Prépare la phrase, et garde-la pour la prochaine fois.',
  },
  {
    id: 'ent-mentore',
    dimension: 'entourage',
    titre: 'Demande à une femme plus avancée un quart d’heure de son temps.',
    pourquoi: 'Un quart d’heure est refusable sans gêne — c’est pour ça qu’on l’accorde.',
    effortMinutes: 45,
    difficulte: 3,
    prerequis: ['ent-deux-femmes'],
    versionReduite: 'Écris-lui une question précise, par message.',
  },
  {
    id: 'ent-couper-lien',
    dimension: 'entourage',
    titre: 'Éloigne-toi d’une personne qui te tire vers le bas. Sans explication publique.',
    pourquoi: 'On devient la moyenne de ceux à qui on parle le plus.',
    effortMinutes: 30,
    difficulte: 3,
    prerequis: [],
    versionReduite: 'Espace simplement les réponses cette semaine.',
  },
]

const PAR_ID = new Map(ACTIONS.map((a) => [a.id, a]))

export function action(id: string): Action {
  const a = PAR_ID.get(id)
  if (!a) throw new Error(`Action inconnue : ${id}`)
  return a
}

export function actionOptionnelle(id: string): Action | undefined {
  return PAR_ID.get(id)
}

export function actionsParDimension(d: DimensionId): Action[] {
  return ACTIONS.filter((a) => a.dimension === d)
}
